services:
  ubuntu:
    image: ubuntu
    container_name: test
    restart: unless-stopped
    tty: true
    # network_mode: "bridge"
    networks:
      - ubuntu-network
    dns:
      - 1.1.1.1
    # networks:
    #   stack_network:
    #     ipv4_address: 10.1.0.2
networks:
  ubuntu-network:
    driver: bridge

# networks:
#   stack_network:
#     ipam:
#       driver: default
#       config:
#         - subnet: 10.1.0.0/24