api:
  dashboard: false
  debug: true

# accessLog:
#   filePath: "/logs/access.log"
#   format: json
#   fields:
#     defaultMode: drop
#     names:
#       RequestHost: keep
#       RequestPath: keep
#       DownstreamStatus: keep

entryPoints:
  http:
    address: ":80"

serversTransport:
  insecureSkipVerify: true

providers:
  file:
    filename: /config.yml