services:
  nginx-01:
    image: nginx
    container_name: web-01
    restart: unless-stopped
    user: 4000:4000
    cpus: 1
    cpu_shares: 256
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    # network_mode: "bridge"
    networks:
      - web-net
    pids_limit: 100
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
      nproc: 100
    devices: []
    cap_drop:
      - all
    security_opt:
      - no-new-privileges
    ports:
      - ${BIND_ADDRESS:-127.0.0.1}:8080:80/tcp
    # read_only: true
    tmpfs:
      - /run
      - /var/cache/nginx
    # volumes:
    #   - /tmp/test/default.conf:/etc/nginx/conf.d/default.conf:ro
    #   - /tmp/test/html:/usr/share/nginx/html:ro

networks:
  web-net:
    driver: bridge
    
