services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    network_mode: host
    dns:
      - 100.100.100.100
    volumes:
      - /opt/docker/volumes/zoraxy/config/:/opt/zoraxy/config/
      - /opt/docker/volumes/zoraxy/plugin/:/opt/zoraxy/plugin/
      - /etc/localtime:/etc/localtime
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      FASTGEOIP: "false"
      LOGROTATE: "25"
