services:
  zoraxy:
    image: zoraxydocker/zoraxy:latest
    container_name: zoraxy
    restart: unless-stopped
    network_mode: host
    # user: 4000:4000

    read_only: false # image does not support
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - apparmor:docker-default
      - no-new-privileges:true

    cpus: 1
    cpu_shares: 256
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    pids_limit: 100
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
      nproc: 100

    dns:
      - 100.100.100.100
    extra_hosts:
      - "host.docker.internal:host-gateway"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    volumes:
      - /opt/docker/volumes/zoraxy/config/:/opt/zoraxy/config/
      - /opt/docker/volumes/zoraxy/plugin/:/opt/zoraxy/plugin/
      - /opt/docker/volumes/zoraxy/logs/:/opt/zoraxy/log/
      - /etc/localtime:/etc/localtime:ro

    environment:
      FASTGEOIP: "false"
      LOGROTATE: "25"
